### ISSUE TITLE
geting error on click of Create Dataset 

### ISSUE THREAD

**Issue by lpuhan** [KalyanMohanty/Face_Recognition#1]
enter your idEOF when reading a line
Traceback (most recent call last):
  File "dataset_capture.py", line 49, in <module>
    cv2.imwrite("dataset/User." + str(face_id) + '.' + str(count) + ".jpg", gray[y:y+h,x:x+w])
NameError: name 'face_id' is not defined
[ WARN:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (674) SourceReaderCB::~SourceReaderCB terminating async callback

**Comment by KalyanMohanty** [comment]
code is fine . first check whether any indentation problem is there. 
secondly if it shows the same error please re name the face_id to some thing you like both in 
**face_id=input('enter your id')**
**cv2.imwrite("dataset/User." + str(face_id) + '.' + str(count) + ".jpg", gray[y:y+h,x:x+w])**
