### ISSUE TITLE
LBPHFaceRecognizer_create  is deprecated i am using : cv2.__version__  : '4.1.1'

### ISSUE THREAD

**Issue by lpuhan** [KalyanMohanty/Face_Recognition#2]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-569b0c9f6d05> in <module>
      3 from PIL import Image;
      4 
----> 5 recognizer = cv2.face.LBPHFaceRecognizer_create()
      6 detector= cv2.CascadeClassifier("haarcascade_frontalface_default.xml");
      7 

AttributeError: module 'cv2.cv2' has no attribute 'face'

**Comment by KalyanMohanty** [comment]
if you are facing **AttributeError: module 'cv2.cv2' has no attribute 'face'** then just uninstall and reinstall opencv-python.
If you still face same error then install **pip install opencv-contrib-python**
